FROM nginx:stable-alpine

COPY ./build/ /usr/share/nginx/html

COPY nginx/default.conf.template /etc/nginx/conf.d/default.conf.template

RUN apk add gettext bash

CMD /bin/bash -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'